// Wallet Action Types
export const FETCH_WALLET_HISTORY = 'FETCH_WALLET_HISTORY';
export const FETCH_WALLET_HISTORY_SUCCESS = 'FETCH_WALLET_HISTORY_SUCCESS';
export const FETCH_WALLET_HISTORY_FAIL = 'FETCH_WALLET_HISTORY_FAIL'; 