#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

ENV_FILE="${ENV_FILE:-${BACKEND_DIR}/.env}"
PORT="${PORT:-3001}"
NODE_ENV="${NODE_ENV:-development}"
SOCKET_IO_ADAPTER="${SOCKET_IO_ADAPTER:-redis}"
MATCH_DRIVERS_PER_WAVE="${MATCH_DRIVERS_PER_WAVE:-3}"
MATCH_RESPONSE_PAUSE_MIN_UNIQUE_DRIVERS="${MATCH_RESPONSE_PAUSE_MIN_UNIQUE_DRIVERS:-3}"
MATCH_INITIAL_RADIUS_KM="${MATCH_INITIAL_RADIUS_KM:-2.5}"
MATCH_MAX_RADIUS_KM="${MATCH_MAX_RADIUS_KM:-5}"
MATCH_EXPANSION_STEP_KM="${MATCH_EXPANSION_STEP_KM:-2.5}"
MATCH_EXPANSION_INTERVAL_MS="${MATCH_EXPANSION_INTERVAL_MS:-8000}"
DISPATCH_DRIVER_RESPONSE_TIMEOUT_SECONDS="${DISPATCH_DRIVER_RESPONSE_TIMEOUT_SECONDS:-300}"
OFFER_RESERVATION_TTL_SECONDS="${OFFER_RESERVATION_TTL_SECONDS:-300}"
DISPATCH_DRIVER_LIVENESS_GRACE_MS="${DISPATCH_DRIVER_LIVENESS_GRACE_MS:-300000}"
DRIVER_DISCONNECT_GRACE_MS="${DRIVER_DISCONNECT_GRACE_MS:-300000}"
DRIVER_STATUS_DEBUG_TOKEN="${DRIVER_STATUS_DEBUG_TOKEN:-leaf-local-driver-status}"
RUNTIME_ADMIN_TOKEN="${RUNTIME_ADMIN_TOKEN:-${DRIVER_STATUS_DEBUG_TOKEN}}"
RESTART_TOKEN="${RESTART_TOKEN:-${DRIVER_STATUS_DEBUG_TOKEN}}"
RATE_LIMIT_HTTP_GENERAL="${RATE_LIMIT_HTTP_GENERAL:-5000}"
RATE_LIMIT_HTTP_WEBSOCKET="${RATE_LIMIT_HTTP_WEBSOCKET:-5000}"
RATE_LIMIT_HTTP_DRIVER_STATUS="${RATE_LIMIT_HTTP_DRIVER_STATUS:-5000}"
RATE_LIMIT_FLOW_CORE="${RATE_LIMIT_FLOW_CORE:-5000}"
RATE_LIMIT_CREATE_BOOKING="${RATE_LIMIT_CREATE_BOOKING:-1000}"
RATE_LIMIT_CONFIRM_PAYMENT="${RATE_LIMIT_CONFIRM_PAYMENT:-1000}"
RATE_LIMIT_ACCEPT_RIDE="${RATE_LIMIT_ACCEPT_RIDE:-1000}"
RATE_LIMIT_SEARCH_DRIVERS="${RATE_LIMIT_SEARCH_DRIVERS:-5000}"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "[mobile-only-e2e-server] env file not found at ${ENV_FILE}" >&2
  exit 1
fi

if lsof -Pi :"${PORT}" -sTCP:LISTEN -t >/dev/null 2>&1; then
  echo "[mobile-only-e2e-server] port ${PORT} is already in use" >&2
  exit 1
fi

echo "[mobile-only-e2e-server] starting backend on port ${PORT}"
echo "[mobile-only-e2e-server] env file: ${ENV_FILE}"
echo "[mobile-only-e2e-server] driversPerWave=${MATCH_DRIVERS_PER_WAVE} minUniqueDrivers=${MATCH_RESPONSE_PAUSE_MIN_UNIQUE_DRIVERS} responseTimeout=${DISPATCH_DRIVER_RESPONSE_TIMEOUT_SECONDS}s reservationTtl=${OFFER_RESERVATION_TTL_SECONDS}s disconnectGrace=${DRIVER_DISCONNECT_GRACE_MS}ms livenessGrace=${DISPATCH_DRIVER_LIVENESS_GRACE_MS}ms"

cd "${BACKEND_DIR}"
exec env \
  ENV_FILE="${ENV_FILE}" \
  PORT="${PORT}" \
  NODE_ENV="${NODE_ENV}" \
  SOCKET_IO_ADAPTER="${SOCKET_IO_ADAPTER}" \
  MATCH_DRIVERS_PER_WAVE="${MATCH_DRIVERS_PER_WAVE}" \
  MATCH_RESPONSE_PAUSE_MIN_UNIQUE_DRIVERS="${MATCH_RESPONSE_PAUSE_MIN_UNIQUE_DRIVERS}" \
  MATCH_INITIAL_RADIUS_KM="${MATCH_INITIAL_RADIUS_KM}" \
  MATCH_MAX_RADIUS_KM="${MATCH_MAX_RADIUS_KM}" \
  MATCH_EXPANSION_STEP_KM="${MATCH_EXPANSION_STEP_KM}" \
  MATCH_EXPANSION_INTERVAL_MS="${MATCH_EXPANSION_INTERVAL_MS}" \
  DISPATCH_DRIVER_RESPONSE_TIMEOUT_SECONDS="${DISPATCH_DRIVER_RESPONSE_TIMEOUT_SECONDS}" \
  OFFER_RESERVATION_TTL_SECONDS="${OFFER_RESERVATION_TTL_SECONDS}" \
  DISPATCH_DRIVER_LIVENESS_GRACE_MS="${DISPATCH_DRIVER_LIVENESS_GRACE_MS}" \
  DRIVER_DISCONNECT_GRACE_MS="${DRIVER_DISCONNECT_GRACE_MS}" \
  DRIVER_STATUS_DEBUG_TOKEN="${DRIVER_STATUS_DEBUG_TOKEN}" \
  RUNTIME_ADMIN_TOKEN="${RUNTIME_ADMIN_TOKEN}" \
  RESTART_TOKEN="${RESTART_TOKEN}" \
  RATE_LIMIT_HTTP_GENERAL="${RATE_LIMIT_HTTP_GENERAL}" \
  RATE_LIMIT_HTTP_WEBSOCKET="${RATE_LIMIT_HTTP_WEBSOCKET}" \
  RATE_LIMIT_HTTP_DRIVER_STATUS="${RATE_LIMIT_HTTP_DRIVER_STATUS}" \
  RATE_LIMIT_FLOW_CORE="${RATE_LIMIT_FLOW_CORE}" \
  RATE_LIMIT_CREATE_BOOKING="${RATE_LIMIT_CREATE_BOOKING}" \
  RATE_LIMIT_CONFIRM_PAYMENT="${RATE_LIMIT_CONFIRM_PAYMENT}" \
  RATE_LIMIT_ACCEPT_RIDE="${RATE_LIMIT_ACCEPT_RIDE}" \
  RATE_LIMIT_SEARCH_DRIVERS="${RATE_LIMIT_SEARCH_DRIVERS}" \
  node server.js
