global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'leaf-websocket'
    static_configs:
      - targets: ['websocket-1:3001', 'websocket-2:3001', 'websocket-3:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s
