apiVersion: 1

notifiers:
  - name: Discord P1
    type: discord
    uid: discord-p1-alerts
    org_id: 1
    is_default: true
    settings:
      url: ${DISCORD_ALERT_WEBHOOK_URL}
      title: 'LEAF Alert'
      message: '{{ .Message }}'

  - name: Slack
    type: slack
    uid: slack-alerts
    org_id: 1
    is_default: false
    settings:
      url: ${SLACK_WEBHOOK_URL}
      username: Grafana
      icon_emoji: ':warning:'
      title: 'LEAF Alert'
      text: '{{ .Message }}'
      channel: '#alerts'
