apiVersion: 1

notifiers:
  - name: Slack
    type: slack
    uid: slack-alerts
    org_id: 1
    is_default: false
    settings:
      url: ${SLACK_WEBHOOK_URL}
      username: Grafana
      icon_emoji: ':warning:'
      title: 'LEAF Alert'
      text: '{{ .Message }}'
      channel: '#alerts'

